name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkstyle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Checkstlye
      run: mvn -B checkstyle:checkstyle
    - name: Upload Checkstlye report
      uses: actions/upload-artifact@v2
      with:
        name: checkstyle-report
        path: target/checkstyle-result.xml
        retention-days: 2

  spotbugs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Spotbugs
      run: mvn -B compile spotbugs:spotbugs
    - name: Upload Spotbugs report
      uses: actions/upload-artifact@v2
      with:
        name: spotbugs-report
        path: target/spotbugs.xml
        retention-days: 2

  jacoco:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Run test to create jacoco.exec
          run: mvn test
        - name: Run Jacoco report goal
          run: mvn -B jacoco:report
        - name: Upload Jacoco report
          uses: actions/upload-artifact@v2
          with:
            name: jacoco-report
            path: target/site/jacoco
            retention-days: 2
